<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => 'اضافة',
    'Incorect email or Token sent' => 'البريد الالكتروني أو رمز التفعيل غير صحيح',
    'Search result' => 'نتائج البحث',
    'Check your email for further instructions.' => 'الرجاء تفقد بريدك الالكتروني لمعرفة كيفية تفعيل حسابك',
    'Check your email for further instructions how to reset your password.' => 'الرجاء تفقد بريدك الالكتروني لمعرفة كيفية تغير كلمة المرور  لحسابك',
    'Thanks you for your registeration {link}' => 'شكرا لك لتسجيلك, تستطيع تسجيل الدخول بالضغط {link}',
    'Sorry, we are unable to reset password for email provided.' => 'البريد الالكتروني المستخدم غير صحيح',
    'Here' => 'هنا',
    'Your account activated successfuly {link}' => 'لقد تم تفعيل حسابك بنجاح.لتسجيل الدخول الرجاء الضغط {link} ',
    'Facebook id' => 'فيسبوك  id',
    'New indicator' => ' مؤشر جديد',
    'Country' => 'البلد',
    'Female' => 'انثى',
    'Gender' => 'الجنس',
    'Governorate' => 'محافظة',
    'Male' => 'ذكر',
    'Change password' => 'تغير كلمة المرور',
    'Confirm password' => 'تأكيد كلمة السر',
    'Contact us' => 'المساعده',
    'Copyrigths reserved' => 'جميع الحقوق محفوظه',
    'Date Of Birth' => 'تاريخ الميلاد',
    'Email' => 'البريد الالكتروني',
    'Forget password' => 'نسيت كلمة المرور؟',
    'Full name' => 'الاسم الكامل',
    'Have account' => 'لديك حساب؟',
    'Incorrect email or password.' => 'خطاء في كلمة المرور أو البريد الالكتروني',
    'Login' => 'دخول',
    'My profile' => 'الملف الشخصي',
    'New password' => 'كلمة السر الجديدة',
    'Old password' => 'كلمة السر الحالية',
    'Old password is invalid' => 'كلمة المرور الحالية غير صحيحة',
    'Password' => 'كلمة المرور',
    'Password updated successfully' => 'تم تعديل كلمة المرور بنجاح',
    'Privacy' => 'الخصوصيه',
    'Profile updated successfully' => 'تم تعديل الملف الشخصي بنجاح',
    'Remember me' => 'تذكر معلوماتي',
    'Sign out' => 'تسجيل الخروج',
    'Signup' => 'سجل',
    'User not found' => 'المستخدم غير موجود',
    'Update photo' => ' تحديث الصورة',
    'Lat' => 'خطوط العرض',
    'Long' => 'خطوط الطول',
    'Address' => 'العنوان',
    'From' => 'من',
    'To' => 'الى',
    'More' => 'المزيد',
    'Send' => 'ارسل',
    'Password reset token cannot be blank.' => 'كود التفعيل لايمكن ان يكون فارغا',
    'Wrong password reset token.' => 'كود التفعيل غير صحيح',
    'New password was saved.' => 'لقد تم تغير كلمة المرور بنجاح',
    'Subject' => 'الموضوع',
    'Thank you for contacting us, we will reply to your request as soon as possible' => 'شكرا لك,سوف يتم الاتصال بك قريبا',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
];
